export const FETCH_APPOINTMENTS_REQUEST = 'FETCH_APPOINTMENTS_REQUEST',
  FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS',
  FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE',
  CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST',
  CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS',
  CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';
