export const FETCH_CLINIC_REQUEST = 'FETCH_CLINIC_REQUEST',
  FETCH_CLINIC_SUCCESS = 'FETCH_CLINIC_SUCCESS',
  FETCH_CLINIC_FAILURE = 'FETCH_CLINIC_FAILURE',
  DELETE_CLINIC_REQUEST = 'DELETE_CLINIC_REQUEST',
  DELETE_CLINIC_SUCCESS = 'DELETE_CLINIC_SUCCESS',
  DELETE_CLINIC_FAILURE = 'DELETE_CLINIC_FAILURE';
