export const FETCH_PATIENTS_REQUEST = 'FETCH_PATIENTS_REQUEST',
  FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS',
  FETCH_PATIENTS_FAILURE = 'FETCH_PATIENTS_FAILURE',
  DELETE_PATIENT_REQUEST = 'DELETE_PATIENT_REQUEST',
  DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS',
  DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';
